name: XcodeBuildCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: '12.3.0'
    - name: Build
      run: |
        xcodebuild clean build -project RSAClient-iOS.xcodeproj -scheme RSAClient-iOS -destination 'platform=iOS Simulator,OS=14.3,name=iPhone X'
    - name: Run Tests
      run: |
        xcodebuild clean test -project RSAClient-iOS.xcodeproj -scheme RSAClient-iOS -destination 'platform=iOS Simulator,OS=14.3,name=iPhone X'
